local addonName, addonTable             = ...

local className, classFilename, classId = UnitClass("player")
local currentSpec                       = GetSpecialization()

if classFilename ~= "PRIEST" then return end

-- PriestDiscipline
if currentSpec == 1 then
    table.insert(addonTable.macroList, { title = "target痛", key = "ALT-NUMPAD1", text = "/cast [@target] 暗言术：痛" })
    table.insert(addonTable.macroList, { title = "focus痛", key = "ALT-NUMPAD2", text = "/cast [@focus] 暗言术：痛" })
    table.insert(addonTable.macroList, { title = "target灭", key = "ALT-NUMPAD3", text = "/cast [@target] 暗言术：灭" })
    table.insert(addonTable.macroList, { title = "focus灭", key = "ALT-NUMPAD4", text = "/cast [@focus] 暗言术：灭" })
    table.insert(addonTable.macroList, { title = "target心灵震爆", key = "ALT-NUMPAD5", text = "/cast [@target] 心灵震爆" })
    table.insert(addonTable.macroList, { title = "focus心灵震爆", key = "ALT-NUMPAD6", text = "/cast [@focus] 心灵震爆" })
    table.insert(addonTable.macroList, { title = "target惩击", key = "ALT-NUMPAD7", text = "/cast [@target] 惩击" })
    table.insert(addonTable.macroList, { title = "focus惩击", key = "ALT-NUMPAD8", text = "/cast [@focus] 惩击" })
    table.insert(addonTable.macroList, { title = "player盾", key = "ALT-NUMPAD9", text = "/cast [@player] 真言术：盾" })
    table.insert(addonTable.macroList, { title = "party1盾", key = "ALT-NUMPAD0", text = "/cast [@party1] 真言术：盾" })
    table.insert(addonTable.macroList, { title = "party2盾", key = "SHIFT-NUMPAD1", text = "/cast [@party2] 真言术：盾" })
    table.insert(addonTable.macroList, { title = "party3盾", key = "SHIFT-NUMPAD2", text = "/cast [@party3] 真言术：盾" })
    table.insert(addonTable.macroList, { title = "party4盾", key = "SHIFT-NUMPAD3", text = "/cast [@party4] 真言术：盾" })
    table.insert(addonTable.macroList, { title = "target苦修", key = "SHIFT-NUMPAD4", text = "/cast [@target] 苦修" })
    table.insert(addonTable.macroList, { title = "focus苦修", key = "SHIFT-NUMPAD5", text = "/cast [@focus] 苦修" })
    table.insert(addonTable.macroList, { title = "player苦修", key = "SHIFT-NUMPAD6", text = "/cast [@player] 苦修" })
    table.insert(addonTable.macroList, { title = "party1苦修", key = "SHIFT-NUMPAD7", text = "/cast [@party1] 苦修" })
    table.insert(addonTable.macroList, { title = "party2苦修", key = "SHIFT-NUMPAD8", text = "/cast [@party2] 苦修" })
    table.insert(addonTable.macroList, { title = "party3苦修", key = "SHIFT-NUMPAD9", text = "/cast [@party3] 苦修" })
    table.insert(addonTable.macroList, { title = "party4苦修", key = "SHIFT-NUMPAD0", text = "/cast [@party4] 苦修" })
    table.insert(addonTable.macroList, { title = "player恳求", key = "ALT-F2", text = "/cast [@player] 恳求" })
    table.insert(addonTable.macroList, { title = "party1恳求", key = "ALT-F3", text = "/cast [@party1] 恳求" })
    table.insert(addonTable.macroList, { title = "party2恳求", key = "ALT-F5", text = "/cast [@party2] 恳求" })
    table.insert(addonTable.macroList, { title = "party3恳求", key = "ALT-F6", text = "/cast [@party3] 恳求" })
    table.insert(addonTable.macroList, { title = "party4恳求", key = "ALT-F7", text = "/cast [@party4] 恳求" })
    table.insert(addonTable.macroList, { title = "player纯净术", key = "ALT-F8", text = "/cast [@player] 纯净术" })
    table.insert(addonTable.macroList, { title = "party1纯净术", key = "ALT-F9", text = "/cast [@party1] 纯净术" })
    table.insert(addonTable.macroList, { title = "party2纯净术", key = "ALT-F10", text = "/cast [@party2] 纯净术" })
    table.insert(addonTable.macroList, { title = "party3纯净术", key = "ALT-F11", text = "/cast [@party3] 纯净术" })
    table.insert(addonTable.macroList, { title = "party4纯净术", key = "ALT-F12", text = "/cast [@party4] 纯净术" })
    table.insert(addonTable.macroList, { title = "player快速治疗", key = "SHIFT-F2", text = "/cast [@player] 快速治疗" })
    table.insert(addonTable.macroList, { title = "party1快速治疗", key = "SHIFT-F3", text = "/cast [@party1] 快速治疗" })
    table.insert(addonTable.macroList, { title = "party2快速治疗", key = "SHIFT-F5", text = "/cast [@party2] 快速治疗" })
    table.insert(addonTable.macroList, { title = "party3快速治疗", key = "SHIFT-F6", text = "/cast [@party3] 快速治疗" })
    table.insert(addonTable.macroList, { title = "party4快速治疗", key = "SHIFT-F7", text = "/cast [@party4] 快速治疗" })
    table.insert(addonTable.macroList, { title = "any切换目标", key = "SHIFT-F8", text = "/targetenemy\n/focus\n/targetlasttarget" })
    table.insert(addonTable.macroList, { title = "any耀", key = "SHIFT-F9", text = "/castsequence [@player] reset=10 真言术：耀,真言术：盾" })
    table.insert(addonTable.macroList, { title = "any绝望祷言", key = "SHIFT-F10", text = "/cast [@player] 绝望祷言" })
    table.insert(addonTable.macroList, { title = "any耐力", key = "SHIFT-F11", text = "/cast [@player] 真言术：韧" })
    table.insert(addonTable.macroList, { title = "any渐隐术", key = "SHIFT-F12", text = "/cast 渐隐术" })
    DISABLE_EZOK = true
end
